### ISSUE TITLE
error: cannot find symbol: private PlayMorphia morphia;

### ISSUE THREAD

**Issue by tanoy009** [morellik/play-morphia#1]
Hi, Thanks for building the morphia plugin. Although when I am trying to integrate this plugin with my play 
 2.5.X java application I am getting an error saying "private PlayMorphia morphi".
my config/application.config is 
```
playmorphia {
    uri="mongodb://127.0.0.1:27017/YourDB"
    database="YourDB"
    models="models"
    mongoClientFactory="controllers.MyMongoClientFactory"
}
```

and i have created the lib folder under my app folder.
If u get time please revert back.

**Comment by morellik** [comment]
I need more information. The exact error with the traceback. Did you put play-morphia.jar into lib folder?  Did you import it.unifi.cerm.playmorphia.PlayMorphia;?

Initially comment the mongoClientFactory line in the application.conf.



-- 
-----------------------------------------------------------
  *Enrico Morelli*
  System Administrator | Programmer | Web Developer

  CERM - Polo Scientifico
  via Sacconi, 6 - 50019 Sesto Fiorentino (FI) - ITALY
------------------------------------------------------------
